version: '3'
services:
  python2:
    build:
      context: .
      args:
        py_major:
        py_ver: 2.7.12-1~16.04
    image: tomdottom/python-build:2.7.12

  python3:
    build:
      context: .
      args:
        py_major: 3
        py_ver: 3.5.1-3
    image: tomdottom/python-build:3.5.1